#!/bin/sh
#inkVerbSerf! verb.ink

# This installs mod_sec and mod_evasive (forked) for Apache security

# How to use:
## ./secapache


# Check if done
if [ -f /opt/verb/conf/secapache ]; then
  . /opt/verb/conf/secapache
else
  SEC_APACHE="no"
  security2_module="no"
  SecRuleEngine="no"
  IncludeOptional="no"
fi

if [ $SEC_APACHE = "done" ]; then
  /bin/echo "Already done."
  exit 0
fi

# mod_sec installation
if [ $security2_module = "done" ]; then
  /bin/echo "Already done."
else

/usr/bin/apt-get install -y libapache2-mod-security2
/bin/systemctl restart apache2
if [ "$(/usr/sbin/apachectl -M | /bin/grep security2_module)" = " security2_module (shared)" ]; then
  /bin/echo "security2_module=\"done\"" > /opt/verb/conf/secapache
else
  /bin/echo "Something's wrong with security2_module, I quit."
  exit 4
fi

fi

# mod_sec
if [ $SecRuleEngine = "done" ]; then
  /bin/echo "Already done."
else

/bin/cp /etc/modsecurity/modsecurity.conf-recommended /etc/modsecurity/modsecurity.conf
/bin/sed -i "s/^SecRuleEngine DetectionOnly/SecRuleEngine On/" /etc/modsecurity/modsecurity.conf
/bin/systemctl restart apache2
if /bin/grep -q "SecRuleEngine On" /etc/modsecurity/modsecurity.conf; then
  /bin/echo "SecRuleEngine=\"done\"" >> /opt/verb/conf/secapache
else
  /bin/echo "Something's wrong with SecRuleEngine, I quit."
  exit 4
fi

fi

# mod_sec rules
if [ $IncludeOptional = "done" ]; then
  /bin/echo "Already done."
else

/bin/mv /usr/share/modsecurity-crs /usr/share/modsecurity-crs.bk
/usr/bin/git clone https://github.com/SpiderLabs/owasp-modsecurity-crs.git /usr/share/modsecurity-crs
if [ ! -d "/usr/share/modsecurity-crs" ]; then
  /bin/echo "Something's wrong with modsecurity-crs, I quit."
  exit 4
fi

if ! /bin/grep -Fq '## inkVerb IncludeOptional' /etc/apache2/mods-enabled/security2.conf; then
  /bin/sed -i "/<\/IfModule>/d" /etc/apache2/mods-enabled/security2.conf
  /bin/echo "
  ## Added by inkVerb
  IncludeOptional /usr/share/modsecurity-crs/*.conf
  IncludeOptional /usr/share/modsecurity-crs/rules/*.conf
  ## inkVerb IncludeOptional
  </IfModule>" >> /etc/apache2/mods-enabled/security2.conf
fi

/bin/systemctl restart apache2
if /bin/grep -Fq 'IncludeOptional /usr/share/modsecurity-crs/*.conf' /etc/apache2/mods-enabled/security2.conf; then
  /bin/echo "IncludeOptional=\"done\"" >> /opt/verb/conf/secapache
else
  /bin/echo "Something's wrong with IncludeOptional, I quit."
  exit 4
fi

fi

# mod_evasive Fork (https://github.com/shivaas/mod_evasive)


# Finish
## Note in the settiongs
/bin/echo "SEC_APACHE=\"done\"" >> /opt/verb/conf/secapache
## Message
/bin/echo "Secure Apache done."
