#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This adds a new domain to the vmail database so it and its mailboxes can be managed in PFA

# How to use:
## ./vmailnewdomain [domain]


domain="$1"
if [ -z "$2" ]; then
description="$1"
else
description="$2"
fi

# Include the config
. /opt/verb/conf/siteurilist

# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

# Make the database entry
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "INSERT INTO domain (domain, description, aliases, mailboxes, maxquota, quota, transport, backupmx, created, modified, active) VALUES ('$domain', '$description', '1000', '1000', '10000', '2048', 'virtual', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO alias (address, goto, domain, created, modified, active) VALUES ('abuse@$domain', 'abuse@$nameURI', '$domain', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO alias (address, goto, domain, created, modified, active) VALUES ('hostmaster@$domain', 'hostmaster@$nameURI', '$domain', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO alias (address, goto, domain, created, modified, active) VALUES ('postmaster@$domain', 'postmaster@$nameURI', '$domain', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO alias (address, goto, domain, created, modified, active) VALUES ('webmaster@$domain', 'webmaster@$nameURI', '$domain', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);"

# Finish
/bin/echo "Domain $domain added to vmail"
