#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This adds a new mailbox to the vmail database

# How to use:
## ./vmailnewmailbox [emailUser (no domain)] [domain] [name - optional]

# Eg:
## ./vmailnewmailbox james inkisaverb.com "James Inksmith"


emailUser="$1"
domain="$2"
if [ -z "$3" ]; then
NAME="$1"
else
NAME="$3"
fi

# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed. Do that first."
  exit 0; fi

# Prep the variables

# Hash the password
PASSWORD=$(/usr/bin/pwgen -s 15)
password="$(/bin/echo $PASSWORD | /usr/bin/openssl passwd -1 -stdin)"
username="$emailUser@$domain"
vmaildirectory="$domain/$emailUser/"
mailboxsize="524288000" # 0.5GB, 2GB=2097152000, 1GB=1048576000, 5GB=5242880000

# Make the database entry
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "INSERT INTO mailbox (username, password, name, maildir, quota, local_part, domain, created, modified, active) VALUES ('$username', '$password', '$NAME', '$vmaildirectory', '$mailboxsize', '$emailUser', '$domain', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO alias (address, goto, domain, created, modified, active) VALUES ('$username', '$username', '$domain', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);"

# Finish
/bin/echo "Created:
User login: $username
Password: $PASSWORD"
