#!/bin/sh
#inkVerbMaker! verb.ink

# This prepares the early settings for the name286.verb.ink or custom Domain Mod server necessary to make the Verber
## This currently takes no parameters
## The basic purpose is to add the universe repo and configure locale in preparation for make-verber

# How to use:
## ./make-verber-preserver


# Directory check
if [ ! -d "/opt/verb" ]; then
/bin/echo "Put the verb directory at /opt/verb first, then try again."
exit 8; fi

# Since we're starting our work, give root the verb link now: save time right at the next login :-)
/bin/ln -s /opt/verb /root/
/bin/ln -s /opt/verb/inst/make-verber /opt/verb/serfs/

# Local
locale-gen en_US en_US.UTF-8
#dpkg-reconfigure locales # This broke the installer with a dialog
## Set up locality
/bin/echo "LANG="en_US.UTF-8"
LANGUAGE="en_US:en"
LC_ALL="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
" > /etc/default/locale

# Add Universe repo
/usr/bin/add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
/usr/bin/apt-get update
/usr/bin/apt-get upgrade -y
dpkg --configure -a
/usr/bin/apt-get autoremove -y

# Restart Server and reconnect at the new port
/bin/echo "
Pre-install is finished and is ready to run make-verber.

Run: reboot

Then log back onto the server to run make-verber.
"

# Delete this one-time script
/bin/rm /opt/verb/inst/make-verber-preserver

